# -*- coding: utf-8 -*-
"""
Created on Fri Sep 28 2018
@author: Tjardo Maarseveen
"""

OTHER_MEDICINE = [
'solumedrol'
]

MEDICINE = [
'methotrexaat', 
'leflunomide', 
'sulfasalazine', 
'hydroxychloroquine',  
'azathioprine', 
'ciclosporine', 
'goud', 
'abatacept', 
'adalimumab', 
'anakinra', 
'certolizumab', 
'etanercept', 
'golimumab', 
'infliximab', 
'rituximab', 
'tocilizumab', 
'tofacitinib', 
'baricitinib', 
'depomedrol', 
'prednison',
'anti-tnf',
'dmard',
'jak-inhibitor',
'corticosteroiden',
'prednisolon' #,
#'biological'
]

# TYPO_MED doesnt include acronyms & goud
TYPO_MED = [
'methotrexaat', 
'leflunomide', 
'sulfasalazine', 
'hydroxychloroquine',  
'azathioprine', 
'ciclosporine', 
'abatacept', 
'adalimumab', 
'anakinra', 
'certolizumab', 
'etanercept', 
'golimumab', 
'infliximab', 
'rituximab', 
'tocilizumab', 
'tofacitinib', 
'baricitinib', 
'depomedrol', 
'prednison',
'prednisolon',
'jak-inhibitor',
'corticosteroiden',
'biological'
]

PARENT_MAP = {
"prednisolon": "prednison"
}

TYPO_ACRONYM_MAP = {
"abx": "abatacept",
"humria": "adalimumab",
"hunira": "adalimumab",
"huimira": "adalimumab",
"humia": "adalimumab",
"huira": "adalimumab",
"humiraa": "adalimumab",
"humar": "adalimumab",
"humiira": "adalimumab",
"humir": "adalimumab",
"hurmira": "adalimumab",
"humari": "adalimumab",
"tnfs": "anti-tnf",
"tnff": "anti-tnf",
"antitnf": "anti-tnf",
"immuran": "azathioprine",
"uimuran": "azathioprine",
"imuarn": "azathioprine",
"bare": "baricitinib",
"cetro": "certolizumab",
"comzia": "certolizumab",
"cmizia": "certolizumab",
"cimizia": "certolizumab",
"cimxia": "certolizumab",
"cizia": "certolizumab",
"cimzea": "certolizumab",
"enoral": "ciclosporine",
"deop": "depomedrol",
"edpo": "depomedrol",
"depom": "depomedrol",
"depoe": "depomedrol",
"depot": "depomedrol",
"depoi": "depomedrol",
"ena": "etanercept",
"embrel": "etanercept",
"enrbel": "etanercept",
"emnbrel": "etanercept",
"ennbrel": "etanercept",
"enbre": "etanercept",
"enberl": "etanercept",
"ebrel": "etanercept",
"symponi": "golimumab",
"symponie": "golimumab",
"hqc": "hydroxychloroquine",
"hsq": "hydroxychloroquine",
"plaquneil": "hydroxychloroquine",
"palquenil": "hydroxychloroquine",
"plauqenil": "hydroxychloroquine",
"plaqeunil": "hydroxychloroquine",
"plaquenyl": "hydroxychloroquine",
"plaquinil": "hydroxychloroquine",
"plquenil": "hydroxychloroquine",
"plaquenik": "hydroxychloroquine",
"plaqueniel": "hydroxychloroquine",
"plaqeuenil": "hydroxychloroquine",
"plaquwnil": "hydroxychloroquine",
"plaquienil": "hydroxychloroquine",
"plaquenuil": "hydroxychloroquine",
"plaeunil": "hydroxychloroquine",
"plqauenil": "hydroxychloroquine",
"plaquenl": "hydroxychloroquine",
"plaqueni": "hydroxychloroquine",
"plaquanil": "hydroxychloroquine",
"ing": "infliximab",
"remicadev": "infliximab",
"remicad": "infliximab",
"araav": "leflunomide",
"lelf": "leflunomide",
"lelfu": "leflunomide",
"mxt": "methotrexaat",
"mtz": "methotrexaat",
"mrx": "methotrexaat",
"mte": "methotrexaat",
"mtc": "methotrexaat",
"pref": "prednison",
"perd": "prednison",
"ored": "prednison",
"prec": "prednison",
"rped": "prednison",
"prendi": "prednison",
"rituxm": "rituximab",
"rtc": "rituximab",
"rimx": "rituximab",
"ssap": "sulfasalazine",
"saz": "sulfasalazine",
"toco": "tocilizumab"
}

ACRONYM_MAP = {
"mtx": "methotrexaat",
"methotrexate": "methotrexaat",
"trexall": "methotrexaat",
"otrexup": "methotrexaat",
"rasuvo": "methotrexaat",
"lef": "leflunomide",
"arava": "leflunomide",
"ara": "leflunomide",
"leflu": "leflunomide",
"lfn": "leflunomide",
"lefl": "leflunomide",
"azulfidine": "sulfasalazine",
"ssz": "sulfasalazine",
"saps": "sulfasalazine",
"ssa": "sulfasalazine",
"sasp": "sulfasalazine",
"hcq": 'hydroxychloroquine',
"plaquenil": 'hydroxychloroquine',
"imuran": "azathioprine",
"ciqorin": "azathioprine",
"aza": "azathioprine",
"neoral": "ciclosporine",
"ciclosp": "ciclosporine",
"au": "goud",
"aba": "abatacept",
"orencia": "abatacept",
"abt": "abatacept",
"humira": "adalimumab",
"ada": "adalimumab",
"kineret": "anakinra",
"ana": "anakinra",
"anti-il1": "anakinra",
"cimzia": "certolizumab",
"certo": "certolizumab",
"enbrel": "etanercept",
"etn": "etanercept",
"eta": "etanercept",
"glm": "golimumab",
"simponi": "golimumab",
"goli": "golimumab",
"remicade": "infliximab",
"inflix": "infliximab",
"ifx": "infliximab",
"infx": "infliximab",
"infl": "infliximab",
"inf": "infliximab",
"rituxan": "rituximab",
"rtx": "rituximab",
"ritux": "rituximab",
"rixm": "rituximab",
"actemra": "tocilizumab",
"tcz": "tocilizumab",
"toci": "tocilizumab",
"tocl": "tocilizumab",
"toc": "tocilizumab",
"xeljanz": "tofacitinib",
"tofa": "tofacitinib",
"olumiant": "baricitinib",
"jak2": "jak-inhibitor",
"jak": "jak-inhibitor",
"jaki": "jak-inhibitor",
"jak-i": "jak-inhibitor",
"bari": "baricitinib",
"depo": "depomedrol",
"medrol": "depomedrol",
"dpm": "depomedrol",
"cortico's": "corticosteroiden",
"corticoid": "corticosteroiden",
"corticoids": "corticosteroiden",
"corticoide": "corticosteroiden",
"corticosteroid": "corticosteroiden",
"pred": "prednison",
"predni": "prednison",
"prednisolon": "prednison",
"tnfi": "anti-tnf",
"atnf": "anti-tnf",
"anti-tnf": "anti-tnf",
"dmard": "dmard",
"dmards": "dmard"
}